my_project/authenticate/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path, reverse_lazy
from . import views
from .forms import LoginForm

from django.contrib.auth.views import (
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)


app_name = 'authenticate'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(template_name='authenticate/login.html', form_class=LoginForm), name='login'),
    path('logout/', LogoutView.as_view(template_name='authenticate/logout.html'), name='logout'),
    path('password-reset/', PasswordResetView.as_view(template_name='authenticate/password_reset.html', email_template_name='authenticate/password_reset_email.html', success_url=reverse_lazy('authenticate:password_reset_done')), name='password-reset'),
    path('password-reset/done', PasswordResetDoneView.as_view(template_name='authenticate/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='authenticate/password_reset_confirm.html', success_url=reverse_lazy('authenticate:password_reset_complete')), name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(template_name='authenticate/password_reset_complete.html'), name='password_reset_complete')
]

my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('auth/', include('authenticate.urls')),
]

my_project/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name='main'),
    path('<int:page>', views.main, name='root_paginate'),
    path('add/', views.add, name='add'),
    path('about/<str:author_name>/', views.get_author, name='author'),
    path('add_author/', views.add_author, name='add_author'),
    path('tag/<str:tag_name>/', views.get_quotes_by_tag, name='tag'),
]

my_project/my_project/templates/my_project/base.html
<!doctype html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
    <title>Document</title>
</head>
<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">
                            Quotes to Scrape
                    </a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    <a href="{% url 'quotes:main' %}" class="btn btn-primary">All quotes</a>
                    {% if user.is_authenticated %}
                    <div class="d-flex align-items-center">
                        <form action="{% url 'authenticate:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-primary me-2">Logout</button>
                        </form>
                    <a href="{% url 'quotes:add' %}" class="btn btn-primary">Add quote</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add author</a>
                    </div>
                    {% else %}
                    <a href="{% url 'authenticate:register' %}" class="btn btn-primary">Register</a>
                    <a href="{% url 'authenticate:login' %}" class="btn btn-primary">Login</a>
                    {% endif %}
                </p>
            </div>
        </div>


{% block content %}
        {% endblock %}
        {% block body %}
{% endblock %}

    </div>
</body>
</html>