my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path('auth/', include('authenticate.urls')),
]

my_project/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.main, name='main'),
    path('<int:page>', views.main, name='root_paginate'),
    path('add/', views.add, name='add'),
    path('about/<str:author_name>/', views.get_author, name='author'),
    path('add_author/', views.add_author, name='add_author'),
    path('tag/<str:tag_name>/', views.get_quotes_by_tag, name='tag'),
]

my_project/quotes/models.py
from django.contrib.auth.models import User
from django.db import models


class Author(models.Model):
    fullname = models.CharField(max_length=50)
    born_date = models.CharField(max_length=50)
    born_location = models.CharField(max_length=50)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, default=None)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=30, unique=True, null=False)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, blank=True, null=True, on_delete=models.CASCADE, default=None)

my_project/quotes/forms.py
from django.db.models import Q
from django.forms import CharField, TextInput, ModelForm, ModelChoiceField, Select, ChoiceField, \
    ModelMultipleChoiceField, SelectMultiple, DateField
from .models import Quote, Author, Tag


class QuotesForm(ModelForm):
    quote = CharField(max_length=300, min_length=3, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    author = ModelChoiceField(queryset=Author.objects.all(), required=True, widget=Select(attrs={'class': 'form-control'}))
    tags = ModelMultipleChoiceField(queryset=Tag.objects.all(), required=False, widget=SelectMultiple(attrs={'class': 'form-control'}))

    class Meta:
        model = Quote
        fields = ('quote', 'tags', 'author')

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super(QuotesForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['author'].queryset = Author.objects.filter(Q(user=user) | Q(user=None))


class AuthorForm(ModelForm):
    fullname = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    born_date = DateField(required=True, widget=TextInput(attrs={'class': 'form-control'}))
    born_location = CharField(max_length=16, min_length=3, required=True, widget=TextInput(attrs={'class': 'form-control'}))
    description = CharField(max_length=300, min_length=3, required=True, widget=TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = Author
        fields = ('fullname', 'born_date', 'born_location', 'description')

my_project/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.db.models import Q, Count
import logging

from .forms import QuotesForm, AuthorForm
from .models import Quote, Author, Tag

logger = logging.getLogger(__name__)


def main(request, page=1):
    if request.user.is_authenticated:
        quotes = Quote.objects.filter(Q(user=request.user) | Q(user=None)).order_by('-created_at')
    else:
        quotes = Quote.objects.filter(user=None).order_by('-created_at')
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.page(page)

    top_ten_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]

    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page, 'tags': top_ten_tags})


@login_required
def add(request):
    form = QuotesForm(instance=Quote(), user=request.user)
    if request.method == 'POST':
        form = QuotesForm(request.POST, instance=Quote(), user=request.user)
        if form.is_valid():
            qu = form.save()
            qu.user = request.user
            qu.save()
            return redirect(to="quotes:main")

    return render(request, 'quotes/add.html', context={"form": form})


def get_author(request, author_name):
    author = Author.objects.get(fullname=author_name)
    return render(request, 'quotes/author.html', context={"author": author})


@login_required
def add_author(request):
    form = AuthorForm(instance=Author())
    if request.method == 'POST':
        form = AuthorForm(request.POST, instance=Author())
        if form.is_valid():
            try:
                aut = form.save()
                aut.user = request.user
                aut.save()
                return redirect(to="quotes:add")
            except Exception as e:
                logger.error("Error while adding author: %s", e)

    return render(request, 'quotes/add_author.html', context={"form": form})


def get_quotes_by_tag(request, tag_name):
    quotes = Quote.objects.filter(tags__name=tag_name)

    return render(request, 'quotes/quotes_by_tag.html', context={"quotes": quotes, "tag_name": tag_name})

my_project/quotes/templates/quotes/add.html
{% extends 'my_project/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Add quote</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Author
            {{ form.author }}
            </label>
        </div>
        <div class="mb-3">
            <label class="form-label">Quote
            {{ form.quote}}
            </label>
        </div>
        <div class="mb-3">
            <label class="form-label">Tags
            {{ form.tags}}
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

my_project/quotes/templates/quotes/add_author.html
{% extends 'my_project/base.html' %}

{% block body %}
<div class="container mt-3">
    <h2>Add author</h2>
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Name
            {{ form.fullname }}
            </label>
        </div>
        <div class="mb-3">
            <label class="form-label">Born date
            {{ form.born_date }}

        <div id="passwordHelpBlock" class="form-text">
              Please enter the date in the format YYYY-MM-DD
        </div>
                </label>
        </div>
      <div class="mb-3">
            <label class="form-label">Born location
            {{ form.born_location }}
            </label>
        </div>
      <div class="mb-3">
            <label class="form-label">Description
            {{ form.description }}
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

my_project/quotes/templates/quotes/author.html
{% extends 'my_project/base.html' %}

{% block body %}

<div class="container">
    <h2>{{ author.fullname }}</h2>
</div>
<div class="container">
   <h3 class="text" itemprop="text">Born date</h3>
    <span class="text" itemprop="text">{{ author.born_date }}</span>
</div>
</div>
<div class="container">
   <h3 class="text" itemprop="text">Born location</h3>
    <span class="text" itemprop="text">{{ author.born_location }}</span>
</div>
<div class="container">
   <h3 class="text" itemprop="text">About</h3>
    <span class="text" itemprop="text">{{ author.description }}</span>
</div>

{% endblock %}

my_project/quotes/templates/quotes/index.html
{% extends 'my_project/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author}}</small>
                <a href="{% url 'quotes:author' author_name=quote.author.fullname %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="{% url 'quotes:tag' tag_name=tag %}">{{tag}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-md-4 tags-box">
        <h2>Top Ten tags</h2>
        {% for tag in tags %}
        <span class="tag-item">
        <a class="tag" style="font-size: 28px" href="{% url 'quotes:tag' tag_name=tag %}">{{tag}}</a>
        </span>
        {% endfor %}
    </div>
</div>
<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
            </li>
            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                   href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next <span aria-hidden="true">→</span></a>
            </li>
        </ul>
    </nav>
</div>

{% endblock %}

my_project/quotes/templates/quotes/quotes_by_tag.html
{% extends 'my_project/base.html' %}
{% load extract %}

{% block content %}

<div class="row">
    <div class="col-md-8">
         <p> Quotes by tag: {{ tag_name }} </p>

        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">{{quote.quote}}</span>
            <span>by <small class="author" itemprop="author">{{quote.author}}</small>
                <a href="{% url 'quotes:author' author_name=quote.author.fullname %}">(about)</a>
            </span>
        </div>
        {% endfor %}
    <nav>
        <ul class="pager">

            <li class="previous">
                <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                   href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}">
                    <span aria-hidden="true">←</span> Previous</a>
            </li>


            <li class="next">
                <a class="{% if not quotes.has_next %} disabled {% endif %}"
                   href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next <span aria-hidden="true">→</span></a>
            </li>

        </ul>
    </nav>
    </div>
</div>

{% endblock %}